---
name: test
on: pull_request
permissions: {}
jobs:
  test:
    uses: ./.github/workflows/workflow_call_test.yaml
    permissions:
      contents: write
    secrets:
      APP_ID: ${{secrets.APP_ID}}
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
  status-check:
    runs-on: ubuntu-24.04
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1
